// frameworks/next-js/components/common/ColorSchemeSelect.tsx
import {
  PSelect,
  PSelectOption,
  type PSelectProps,
  type SelectChangeEventDetail,
} from '@porsche-design-system/components-react/ssr';
import type { ColorScheme } from '@/models/colorScheme';

type ColorSchemeSelectProps = {
  value: ColorScheme;
  onChange: (event: CustomEvent<SelectChangeEventDetail>) => void;
} & Partial<PSelectProps>;

export const ColorSchemeSelect = ({ value = 'scheme-light-dark', onChange, ...rest }: ColorSchemeSelectProps) => {
  return (
    <PSelect name="color-scheme" value={value} onChange={onChange} label="Color Scheme" compact={true} {...rest}>
      <PSelectOption value="scheme-light">Light</PSelectOption>
      <PSelectOption value="scheme-dark">Dark</PSelectOption>
      <PSelectOption value="scheme-light-dark">Light Dark</PSelectOption>
    </PSelect>
  );
};

// frameworks/vue/src/components/common/ColorSchemeSelect.vue
<script setup lang="ts">
import { PSelect, PSelectOption, type SelectChangeEventDetail } from '@porsche-design-system/components-vue';
import type { ColorScheme } from '@/models/colorScheme.ts';
import { useColorSchemeStore } from '@/stores/color-scheme.ts';

const colorSchemeStore = useColorSchemeStore();

const onChange = (e: CustomEvent<SelectChangeEventDetail>) => {
  colorSchemeStore.setColorScheme(e.detail.value as ColorScheme);
};
</script>

<template>
  <PSelect name="color-scheme" :value="colorSchemeStore.colorScheme.value" label="Color Scheme" :compact="true" class="w-48" @change="onChange">
    <PSelectOption value="scheme-light">Light</PSelectOption>
    <PSelectOption value="scheme-dark">Dark</PSelectOption>
    <PSelectOption value="scheme-light-dark">Light Dark</PSelectOption>
  </PSelect>
</template>
